backend:
  name: git-gateway
  branch: main

# This allows you to use the CMS locally on your computer
local_backend: true

# Media files will be stored in this folder in your repo
media_folder: "assets/uploads"
# This path is public, so your website can find the images
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.json"
        fields:
          - { label: "Hero Heading", name: "heading", widget: "string" }
          - { label: "Hero Subheading", name: "subheading", widget: "string", required: false }
          - { label: "Hero Image", name: "hero_image", widget: "image", required: false }
